"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,CalendarDays,Check,ChevronRight,Clapperboard,CreditCard,Heart,LayoutDashboard,LogOut,MapPin,Minus,Plus,QrCode,Search,Share2,ShieldCheck,Sparkles,Ticket,Trash2,UserRound,Users,X,Zap} from "lucide-react";

const seedEvents=[
 {id:1,type:"LIVE MUSIC",title:"Afterlight",sub:"A one-night audiovisual arena experience",date:"SAT · 28 SEP",venue:"Nova Arena",city:"Bengaluru",price:1499,color:"coral"},
 {id:2,type:"THEATRE",title:"The Last Monsoon",sub:"An immersive story staged in the round",date:"FRI · 04 OCT",venue:"Ranga Shankara",city:"Bengaluru",price:899,color:"wine"},
 {id:3,type:"COMEDY",title:"Mostly Honest",sub:"A sharp new hour by four breakout comics",date:"SUN · 06 OCT",venue:"Good Shepherd Auditorium",city:"Bengaluru",price:699,color:"copper"},
 {id:4,type:"SPORT",title:"City Derby",sub:"The loudest football night of the season",date:"SAT · 12 OCT",venue:"Kanteerava Stadium",city:"Bengaluru",price:1099,color:"wine"},
 {id:5,type:"MOVIE",title:"Astra: First Signal",sub:"Premiere screening and cast conversation",date:"FRI · 18 OCT",venue:"PVR Director's Cut",city:"Mumbai",price:549,color:"coral"},
 {id:6,type:"LIVE MUSIC",title:"Indigo Rooms",sub:"An intimate jazz and soul residency",date:"SAT · 19 OCT",venue:"The Lalit Lawns",city:"Delhi",price:1299,color:"copper"},
 {id:7,type:"FOOD",title:"The Night Market",sub:"Thirty chefs, one open-air feast",date:"SUN · 20 OCT",venue:"Jayamahal Palace",city:"Bengaluru",price:399,color:"copper"},
 {id:8,type:"WORKSHOP",title:"Frame by Frame",sub:"A hands-on filmmaking lab",date:"SAT · 26 OCT",venue:"BIC, Domlur",city:"Bengaluru",price:799,color:"wine"},
 {id:9,type:"DANCE",title:"Rhythm & Ritual",sub:"Classical dance in a new light",date:"SUN · 27 OCT",venue:"NCPA Experimental Theatre",city:"Mumbai",price:1199,color:"coral"},
 {id:10,type:"LIVE MUSIC",title:"Rooftop Sessions",sub:"Indie favourites above the city",date:"FRI · 01 NOV",venue:"Skyline Social",city:"Hyderabad",price:999,color:"copper"},
 {id:11,type:"ART",title:"New Perspectives",sub:"An after-hours gallery opening",date:"SAT · 02 NOV",venue:"Kiran Nadar Museum",city:"Delhi",price:499,color:"wine"},
 {id:12,type:"EXHIBITION",title:"The Wonder Lab",sub:"A science museum night for everyone",date:"SUN · 03 NOV",venue:"Visvesvaraya Museum",city:"Bengaluru",price:349,color:"coral"}
];
const seats=Array.from({length:72},(_,i)=>({id:`${String.fromCharCode(65+Math.floor(i/12))}${i%12+1}`,price:Math.floor(i/24)===0?2499:Math.floor(i/24)===1?1899:1499,blocked:[4,10,17,24,31,42,55,63].includes(i)}));
type EventItem=(typeof seedEvents)[number];
type Session={name:string;email:string;role:"customer"|"admin"};
type Order={id:string;event:EventItem;seats:string[];total:number;createdAt:string};
type View="discover"|"seats"|"room"|"tickets"|"studio"|"profile";

export default function Home(){
 const[events,setEvents]=useState<EventItem[]>(seedEvents);const[view,setView]=useState<View>("discover");const[selectedEvent,setSelectedEvent]=useState<EventItem>(seedEvents[0]);const[selected,setSelected]=useState<string[]>([]);const[favs,setFavs]=useState<number[]>([]);const[toast,setToast]=useState("");const[checkout,setCheckout]=useState(false);const[orders,setOrders]=useState<Order[]>([]);const[query,setQuery]=useState("");const[category,setCategory]=useState("All scenes");const[city,setCity]=useState("All cities");const[sort,setSort]=useState("Featured");const[cityOpen,setCityOpen]=useState(false);const[user,setUser]=useState<Session|null>(null);const[ready,setReady]=useState(false);const[role,setRole]=useState<"customer"|"admin">("customer");const[name,setName]=useState("");const[email,setEmail]=useState("");const[showEventForm,setShowEventForm]=useState(false);const[editingId,setEditingId]=useState<number|null>(null);const[newTitle,setNewTitle]=useState("");const[newVenue,setNewVenue]=useState("");const[newCity,setNewCity]=useState("Bengaluru");const[newDate,setNewDate]=useState("");const[newPrice,setNewPrice]=useState("999");
 const total=useMemo(()=>selected.reduce((sum,id)=>sum+(seats.find(s=>s.id===id)?.price||0),0),[selected]);
 const soldSeats=orders.reduce((sum,order)=>sum+order.seats.length,0);
 const grossSales=orders.reduce((sum,order)=>sum+order.total,0);
 const[voted,setVoted]=useState(false);
 const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),2200)};
 const chooseEvent=(event:typeof events[0])=>{setSelectedEvent(event);setSelected([]);go("seats")};
 const toggleSeat=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):current.length<6?[...current,id]:(notify("Maximum 6 seats per booking"),current));
 const filtered=events.filter(e=>(category==="All scenes"||category==="Saved"&&favs.includes(e.id)||e.type.includes(category.toUpperCase().replace("MUSIC","LIVE MUSIC").replace("MOVIES","MOVIE")))&&(city==="All cities"||e.city===city)&&(e.title+e.type+e.venue+e.city).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="Price: low"?a.price-b.price:sort==="Price: high"?b.price-a.price:a.id-b.id);
 const go=(next:View)=>{setView(next);history.pushState({},"",`#/${next}`);window.scrollTo({top:0,behavior:"smooth"})};
 const signIn=()=>{if(!email.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)){notify("Enter a valid email address");return}const session:Session={name:name.trim()||email.split("@")[0],email:email.trim().toLowerCase(),role};localStorage.setItem("scenepass_session",JSON.stringify(session));setUser(session);setFavs(JSON.parse(localStorage.getItem(`scenepass_favourites_${session.email}`)||"[]"));setOrders(JSON.parse(localStorage.getItem(session.role==="admin"?"scenepass_all_orders":`scenepass_orders_${session.email}`)||"[]"));go(role==="admin"?"studio":"discover")};
 const signOut=()=>{localStorage.removeItem("scenepass_session");setUser(null);setFavs([]);setOrders([]);setView("discover")};
 const openEventForm=(event?:EventItem)=>{setEditingId(event?.id??null);setNewTitle(event?.title??"");setNewVenue(event?.venue??"");setNewCity(event?.city??"Bengaluru");setNewDate(event?.date??"");setNewPrice(String(event?.price??999));setShowEventForm(true)};
 const addEvent=()=>{if(newTitle.trim().length<3||newVenue.trim().length<3||!newDate.trim()||Number(newPrice)<1){notify("Complete all event fields");return}const item:EventItem={id:editingId??Date.now(),type:events.find(e=>e.id===editingId)?.type??"LIVE MUSIC",title:newTitle.trim(),sub:events.find(e=>e.id===editingId)?.sub??"A new ScenePass live experience",date:newDate.trim(),venue:newVenue.trim(),city:newCity,price:Number(newPrice),color:events.find(e=>e.id===editingId)?.color??"wine"};const next=editingId?events.map(e=>e.id===editingId?item:e):[...events,item];setEvents(next);localStorage.setItem("scenepass_events_v2",JSON.stringify(next));setShowEventForm(false);notify(editingId?"Event updated":"Event published to Discover")};
 const removeEvent=(id:number)=>{const next=events.filter(e=>e.id!==id);setEvents(next);localStorage.setItem("scenepass_events_v2",JSON.stringify(next));notify("Event unpublished")};
 const completeBooking=()=>{const order:Order={id:`SP-${Date.now().toString().slice(-8)}`,event:selectedEvent,seats:[...selected],total,createdAt:new Date().toLocaleDateString("en-IN")};const next=[order,...orders];setOrders(next);localStorage.setItem(`scenepass_orders_${user?.email}`,JSON.stringify(next));const all:Order[]=JSON.parse(localStorage.getItem("scenepass_all_orders")||"[]");localStorage.setItem("scenepass_all_orders",JSON.stringify([order,...all]));setCheckout(false);go("tickets");notify("Booking confirmed · tickets ready")};
 useEffect(()=>{const sync=()=>{const next=location.hash.replace("#/","") as View;if(["discover","seats","room","tickets","studio","profile"].includes(next))setView(next)};sync();addEventListener("popstate",sync);try{const raw=localStorage.getItem("scenepass_session");if(raw){const session:Session=JSON.parse(raw);setUser(session);setFavs(JSON.parse(localStorage.getItem(`scenepass_favourites_${session.email}`)||"[]"));setOrders(JSON.parse(localStorage.getItem(session.role==="admin"?"scenepass_all_orders":`scenepass_orders_${session.email}`)||"[]"))}const storedEvents=localStorage.getItem("scenepass_events_v2");if(storedEvents)setEvents(JSON.parse(storedEvents))}catch{localStorage.removeItem("scenepass_session")}finally{setReady(true)}return()=>removeEventListener("popstate",sync)},[]);
 useEffect(()=>{if(ready&&user)localStorage.setItem(`scenepass_favourites_${user.email}`,JSON.stringify(favs))},[favs,ready,user]);
 useEffect(()=>{if(!user)return;if(user.role==="admin"&&!['studio','profile'].includes(view))setView("studio");if(user.role==="customer"&&view==="studio")setView("discover")},[user,view]);
 useEffect(()=>{if(location.hash!==`#/${view}`)history.replaceState({},"",`#/${view}`)},[view]);
 if(!ready)return <main className="loading-screen"><span>SCENEPASS</span></main>;
 if(!user)return <main className="auth-shell"><section className="auth-visual"><div className="auth-brand"><span>S</span>SCENE<em>PASS</em></div><div><span className="auth-kicker">THE CITY, LIVE</span><h1>Don&apos;t just watch.<br/><em>Be there.</em></h1><p>Discover the night. Pick your seat. Keep every memory close.</p></div><div className="auth-proof"><span>CURATED EVENTS</span><span>GROUP BOOKING</span><span>INSTANT TICKETS</span></div></section><section className="auth-form"><span className="auth-kicker">WELCOME TO SCENEPASS</span><h2>Your next night starts here.</h2><p>Choose a local demo account to explore the experience.</p><div className="role-switch"><button className={role==="customer"?"active":""} onClick={()=>setRole("customer")}><UserRound size={19}/> Customer</button><button className={role==="admin"?"active":""} onClick={()=>setRole("admin")}><ShieldCheck size={19}/> Organizer</button></div><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Aditya Sharma"/></label><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&signIn()} placeholder="you@example.com" type="email"/></label><button className="auth-submit" onClick={signIn}>Continue as {role}<ChevronRight size={19}/></button><small><ShieldCheck size={14}/> Demo sign-in on this device · no password required</small></section>{toast&&<div className="toast"><Sparkles size={16}/>{toast}</div>}</main>;
 return <main className="shell">
  <header className="top"><button className="logo" onClick={()=>go(user.role==="admin"?"studio":"discover")}><span>S</span>SCENE<em>PASS</em></button><nav>{(user.role==="admin"?[["studio","Dashboard"]]:[["discover","Discover"],["room","Group room"],["tickets","My tickets"]]).map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>go(id as View)}>{label}</button>)}</nav><div className="top-actions"><div className="city-switcher"><button className="location" aria-expanded={cityOpen} onClick={()=>setCityOpen(x=>!x)}><MapPin size={15}/>{city}<ChevronRight size={13}/></button>{cityOpen&&<div className="city-menu">{["All cities","Bengaluru","Mumbai","Delhi","Hyderabad"].map(option=><button key={option} onClick={()=>{setCity(option);setCityOpen(false);if(user.role==="customer")go("discover")}}>{option}</button>)}</div>}</div><button className="avatar" aria-label="Open profile" onClick={()=>go("profile")}>{user.name.slice(0,2).toUpperCase()}</button><button className="logout" title="Log out" onClick={signOut}><LogOut size={17}/></button></div></header>
  <div className="demo-banner"><Sparkles size={14}/> Local product demo · accounts, events, bookings and seats are not connected to a live service</div>

  {view==="discover"&&<section className="discover"><div className="hero"><img src="/scene-hero.png" alt="Singer performing beneath a circular light installation"/><div className="hero-shade"></div><div className="hero-copy"><span><i></i> SCENEPASS ORIGINAL · ONE NIGHT ONLY</span><h1>Hear the light.<br/><em>Feel the room.</em></h1><p>Afterlight transforms Nova Arena into a living field of sound, movement and light.</p><div><button onClick={()=>chooseEvent(events[0])}>Choose your seats <ChevronRight size={17}/></button><button className="ghost" onClick={()=>setView("room")}><Users size={17}/> Start a group room</button></div></div><div className="hero-date"><b>28</b><span>SEP<br/>SAT · 8 PM</span></div></div>
  <div className="discover-bar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events, artists or venues"/></div><label className="sort-control">Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price: low</option><option>Price: high</option></select></label></div>
  <div className="chips discover-chips">{["All scenes","Music","Movies","Theatre","Comedy","Sport","Food","Workshop","Dance","Art","Saved"].map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div>
  <section className="event-section"><header><div><span>EXPLORE THE LINEUP</span><h2>Find your next story.</h2></div><p>{filtered.length} experiences {city==="All cities"?"across India":`in ${city}`}</p></header><div className="event-grid">{filtered.map(event=>{const art=(event.id-1)%12;return <article key={event.id} className={`event-card ${event.color}`} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")chooseEvent(event)}} onClick={()=>chooseEvent(event)}><div className="poster" style={{backgroundPosition:`${(art%4)*33.333}% ${Math.floor(art/4)*50}%`}}><span>{event.type}</span><button aria-label={`Save ${event.title}`} onClick={e=>{e.stopPropagation();setFavs(x=>x.includes(event.id)?x.filter(n=>n!==event.id):[...x,event.id])}}><Heart size={18} fill={favs.includes(event.id)?"currentColor":"none"}/></button></div><div className="event-copy"><small>{event.date} · {event.city}</small><h3>{event.title}</h3><p>{event.sub}</p><footer><span><MapPin size={14}/>{event.venue}</span><b>₹{event.price.toLocaleString("en-IN")} <ChevronRight size={15}/></b></footer></div></article>})}</div>{!filtered.length&&<div className="browse-empty"><Search size={28}/><h3>No experiences found</h3><p>Try another city, category or search term.</p><button onClick={()=>{setQuery("");setCategory("All scenes");setCity("All cities")}}>Clear filters</button></div>}</section></section>}

  {view==="seats"&&<section className="seat-page"><header className="seat-head"><button onClick={()=>setView("discover")}><ArrowLeft size={18}/></button><div><small>{selectedEvent.type} · {selectedEvent.date}</small><h1>{selectedEvent.title}</h1><p>{selectedEvent.venue}</p></div><div className="room-people"><span>YOU</span><span>NK</span><span>JM</span><button onClick={()=>setView("room")}><Plus size={14}/></button></div></header><div className="seat-layout"><section className="seat-map"><div className="screen"><span>STAGE</span></div><div className="seat-legend"><span><i className="available"></i>Available</span><span><i className="selected"></i>Your seats</span><span><i className="held"></i>Held by friend</span><span><i className="blocked"></i>Unavailable</span></div><div className="seat-grid">{seats.map((seat,i)=><button key={seat.id} disabled={seat.blocked} title={`${seat.id} · ₹${seat.price}`} className={`${selected.includes(seat.id)?"selected":""} ${[19,38].includes(i)?"held":""}`} onClick={()=>toggleSeat(seat.id)}><span>{seat.id}</span></button>)}</div><div className="tiers"><span>PLATINUM · ₹2,499</span><span>GOLD · ₹1,899</span><span>SILVER · ₹1,499</span></div></section><aside className="booking-panel"><span>LIVE SEAT ROOM</span><h2>Build your perfect row.</h2><div className="timer"><Zap size={17}/><div><b>Seats lock for 06:42</b><small>Synced across everyone in your room</small></div></div><div className="selection"><header><span>YOUR SELECTION</span><b>{selected.length}/6</b></header>{selected.length?selected.map(id=><div key={id}><span><b>{id}</b><small>{seats.find(s=>s.id===id)?.price===2499?"Platinum":seats.find(s=>s.id===id)?.price===1899?"Gold":"Silver"}</small></span><strong>₹{seats.find(s=>s.id===id)?.price}</strong><button onClick={()=>toggleSeat(id)}><X size={14}/></button></div>):<p>Select seats from the map to continue.</p>}</div><div className="price"><span>Total</span><b>₹{total.toLocaleString("en-IN")}</b></div><button className="continue" disabled={!selected.length} onClick={()=>setCheckout(true)}>Continue to payment <ChevronRight size={17}/></button><small className="safe"><Check size={13}/> No convenience fee in this demo</small></aside></div></section>}

  {view==="room"&&<section className="simple-page"><div className="page-kicker"><Users/> GROUP BOOKING PREVIEW</div><h1>Book together.<br/><em>Decide without chaos.</em></h1><p>Preview a group seat vote. Shared rooms are simulated in this local demo.</p><div className="room-board"><section><header><span>DEMO ROOM SP–9248</span><button onClick={()=>{navigator.clipboard?.writeText(`${location.origin}/#/room`);notify("Demo room link copied")}}><Share2 size={15}/> Copy invite</button></header><div className="member"><span>YOU</span><div><b>{user.name}</b><small>Host · {selected.length} seats selected</small></div><em>READY</em></div><div className="member"><span>NK</span><div><b>Nina · demo participant</b><small>Viewing Row C</small></div><em>CHOOSING</em></div><div className="member"><span>JM</span><div><b>Jay · demo participant</b><small>Voted for C7–C10</small></div><em>READY</em></div><button className="continue" onClick={()=>go("seats")}>Open seat map</button></section><aside><span>GROUP VOTE · DEMO</span><h2>Row C · seats 7–10</h2><div className="vote"><b>{voted?"4 of 4":"3 of 4"} agree</b><i><em style={{width:voted?"100%":"75%"}}/></i></div><button onClick={()=>{setVoted(x=>!x);notify(voted?"Vote removed":"Vote recorded")}}>{voted?"Remove my vote":"Vote for these seats"}</button></aside></div></section>}

  {view==="tickets"&&<section className="simple-page"><div className="page-kicker"><Ticket/> YOUR WALLET</div><h1>Every ticket.<br/><em>Ready at the door.</em></h1>{orders.length?<><div className="ticket-card"><div><span>SCENEPASS · ADMIT {orders[0].seats.length}</span><h2>{orders[0].event.title}</h2><p>{orders[0].event.date} · {orders[0].event.venue}</p><b>{orders[0].seats.join(" · ")}</b></div><QrCode size={92}/></div><div className="order-history"><h2>Booking history</h2>{orders.map(order=><article key={order.id}><div><b>{order.event.title}</b><small>{order.id} · {order.createdAt} · {order.seats.join(", ")}</small></div><strong>{order.total?`₹${order.total.toLocaleString("en-IN")}`:"Confirmed"}</strong></article>)}</div></>:<div className="empty-state"><Ticket size={42}/><h2>No tickets yet</h2><p>Your confirmed bookings and offline QR passes will live here.</p><button onClick={()=>go("discover")}>Discover events</button></div>}</section>}

  {view==="profile"&&<section className="simple-page profile-page"><div className="profile-hero"><div className="profile-avatar">{user.name.slice(0,2).toUpperCase()}</div><div><span className="page-kicker">{user.role.toUpperCase()} ACCOUNT</span><h1>{user.name}</h1><p>{user.email} · Bengaluru</p></div><button onClick={signOut}><LogOut size={17}/> Log out</button></div><div className="profile-grid"><article><Heart/><b>{favs.length}</b><span>Saved experiences</span><button onClick={()=>{setCategory("Saved");go("discover")}}>View saved <ChevronRight size={15}/></button></article><article><Ticket/><b>{orders.length}</b><span>Confirmed bookings</span><button onClick={()=>go("tickets")}>Open wallet <ChevronRight size={15}/></button></article><article><MapPin/><b>Bengaluru</b><span>Your city</span><button onClick={()=>notify("More cities coming soon")}>Location settings <ChevronRight size={15}/></button></article></div><div className="profile-note"><ShieldCheck size={18}/> This is a local demo profile. Account data stays in this browser.</div></section>}
  {view==="studio"&&user.role==="admin"&&<section className="simple-page studio"><div className="studio-heading"><div><div className="page-kicker"><LayoutDashboard/> ORGANIZER STUDIO · LOCAL DEMO</div><h1>Organizer overview.</h1></div><button onClick={()=>openEventForm()}><Plus size={17}/> Create event</button></div><div className="metrics"><article><span>DEMO SALES</span><b>₹{grossSales.toLocaleString("en-IN")}</b><em>{orders.length} orders</em></article><article><span>TICKETS SOLD</span><b>{soldSeats}</b><em>on this device</em></article><article><span>PUBLISHED EVENTS</span><b>{events.length}</b><em>available to browse</em></article></div><div className="studio-grid"><section><header><h2>Sample sales trend</h2><span>Illustrative data</span></header><div className="bars">{[42,58,47,71,64,82,94].map((h,i)=><i key={i} style={{height:`${h}%`}}><span>{["M","T","W","T","F","S","S"][i]}</span></i>)}</div></section><aside><h2>Operations preview</h2>{["Entry gates","Scanner devices","Food counters","Support crew"].map((x,i)=><div key={x}><span><Check size={14}/>{x}</span><b>{i===2?"8 / 10":"Ready"}</b></div>)}</aside></div><div className="admin-events"><header><div><span>EVENT INVENTORY</span><h2>Published experiences</h2></div><b>{events.length} active</b></header>{events.map(e=><article key={e.id}><div><b>{e.title}</b><small>{e.date} · {e.venue}</small></div><em>₹{e.price}</em><button title={`Edit ${e.title}`} onClick={()=>openEventForm(e)}>Edit</button><button title={`Unpublish ${e.title}`} onClick={()=>removeEvent(e.id)}><Trash2 size={17}/></button></article>)}</div></section>}
  {view==="studio"&&user.role!=="admin"&&<section className="simple-page empty-state"><ShieldCheck size={40}/><h2>Organizer access only</h2><button onClick={()=>go("discover")}>Back to Discover</button></section>}

  {checkout&&<div className="modal"><section><button className="close" onClick={()=>setCheckout(false)}><X/></button><span>DUMMY CHECKOUT · NO REAL CHARGE</span><h2>One step from the scene.</h2><div className="pay-row"><CreditCard/><span><b>Demo card</b><small>4242 4242 4242 4242</small></span><Check/></div><div className="split"><Users/><span><b>Split with your group</b><small>Demo invite links only</small></span><button onClick={()=>notify("Demo split link created")}><Plus/></button></div><div className="modal-total"><span>{selected.length} tickets</span><b>₹{total.toLocaleString("en-IN")}</b></div><button className="pay" onClick={completeBooking}>Complete dummy payment</button></section></div>}
  {showEventForm&&<div className="modal"><section><button className="close" aria-label="Close" onClick={()=>setShowEventForm(false)}><X/></button><span>ORGANIZER STUDIO</span><h2>{editingId?"Edit experience":"Publish a new event"}.</h2><label className="event-field">Event title<input autoFocus value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Midnight Sessions"/></label><label className="event-field">Date and time<input value={newDate} onChange={e=>setNewDate(e.target.value)} placeholder="SAT · 02 NOV · 8 PM"/></label><label className="event-field">Venue<input value={newVenue} onChange={e=>setNewVenue(e.target.value)} placeholder="Bengaluru International Centre"/></label><label className="event-field">City<select value={newCity} onChange={e=>setNewCity(e.target.value)}>{["Bengaluru","Mumbai","Delhi","Hyderabad"].map(option=><option key={option}>{option}</option>)}</select></label><label className="event-field">Starting price (₹)<input type="number" min="1" value={newPrice} onChange={e=>setNewPrice(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addEvent()}/></label><button className="pay" onClick={addEvent}>{editingId?"Save changes":"Publish event"}</button></section></div>}
  <nav className="mobile-nav">{(user.role==="admin"?[["studio",LayoutDashboard,"Studio"],["profile",UserRound,"Profile"]]:[["discover",Clapperboard,"Discover"],["room",Users,"Room"],["tickets",Ticket,"Tickets"],["profile",UserRound,"Profile"]]).map(([id,Icon,label])=>{const NavIcon=Icon as typeof Ticket;return <button key={id as string} className={view===id?"active":""} onClick={()=>go(id as View)}><NavIcon size={18}/><span>{label as string}</span></button>})}</nav>
  {toast&&<div className="toast"><Sparkles size={16}/>{toast}</div>}
 </main>
}
