import { ART_BY_CATEGORY, COLORS, buildTiers, pickBlockedSeats } from "./catalog.js";

const VENUES = {
  nova: { venue: "Nova Arena", address: "Hebbal Outer Ring Road", city: "Bengaluru", rows: 10, seatsPerRow: 16 },
  ranga: { venue: "Ranga Shankara", address: "JP Nagar 2nd Phase", city: "Bengaluru", rows: 8, seatsPerRow: 12 },
  shepherd: { venue: "Good Shepherd Auditorium", address: "Museum Road", city: "Bengaluru", rows: 8, seatsPerRow: 14 },
  kanteerava: { venue: "Kanteerava Stadium", address: "Kasturba Road", city: "Bengaluru", rows: 10, seatsPerRow: 18 },
  jayamahal: { venue: "Jayamahal Palace Grounds", address: "Jayamahal Main Road", city: "Bengaluru", rows: 8, seatsPerRow: 14 },
  bic: { venue: "Bangalore International Centre", address: "Domlur 2nd Stage", city: "Bengaluru", rows: 6, seatsPerRow: 10 },
  vism: { venue: "Visvesvaraya Museum", address: "Kasturba Road", city: "Bengaluru", rows: 6, seatsPerRow: 12 },
  ncpa: { venue: "NCPA Experimental Theatre", address: "Nariman Point", city: "Mumbai", rows: 8, seatsPerRow: 12 },
  jioworld: { venue: "Jio World Garden", address: "Bandra Kurla Complex", city: "Mumbai", rows: 10, seatsPerRow: 16 },
  habitat: { venue: "The Habitat", address: "Khar West", city: "Mumbai", rows: 6, seatsPerRow: 12 },
  pvr: { venue: "PVR Director's Cut", address: "Infiniti Mall, Andheri West", city: "Mumbai", rows: 8, seatsPerRow: 14 },
  opera: { venue: "Royal Opera House", address: "Girgaon", city: "Mumbai", rows: 8, seatsPerRow: 14 },
  wankhede: { venue: "Wankhede Stadium", address: "Churchgate", city: "Mumbai", rows: 10, seatsPerRow: 18 },
  lalit: { venue: "The Lalit Lawns", address: "Barakhamba Avenue", city: "Delhi", rows: 8, seatsPerRow: 14 },
  knma: { venue: "Kiran Nadar Museum of Art", address: "Saket", city: "Delhi", rows: 6, seatsPerRow: 12 },
  sirifort: { venue: "Siri Fort Auditorium", address: "August Kranti Marg", city: "Delhi", rows: 9, seatsPerRow: 16 },
  kamani: { venue: "Kamani Auditorium", address: "Copernicus Marg", city: "Delhi", rows: 8, seatsPerRow: 12 },
  jln: { venue: "JLN Stadium", address: "Lodhi Road", city: "Delhi", rows: 10, seatsPerRow: 18 },
  skyline: { venue: "Skyline Social", address: "Jubilee Hills", city: "Hyderabad", rows: 6, seatsPerRow: 12 },
  shilpakala: { venue: "Shilpakala Vedika", address: "HITEC City", city: "Hyderabad", rows: 8, seatsPerRow: 14 },
  gachibowli: { venue: "GMC Balayogi Stadium", address: "Gachibowli", city: "Hyderabad", rows: 10, seatsPerRow: 18 },
  prasads: { venue: "Prasads Large Screen", address: "Necklace Road", city: "Hyderabad", rows: 9, seatsPerRow: 16 },
  balgandharva: { venue: "Balgandharva Rangmandir", address: "Shivajinagar", city: "Pune", rows: 8, seatsPerRow: 12 },
  mahalaxmi: { venue: "Mahalaxmi Lawns", address: "Karve Nagar", city: "Pune", rows: 10, seatsPerRow: 16 },
  highspirits: { venue: "The High Spirits", address: "Koregaon Park", city: "Pune", rows: 6, seatsPerRow: 12 },
  academy: { venue: "The Music Academy", address: "TTK Road, Alwarpet", city: "Chennai", rows: 9, seatsPerRow: 14 },
  kalakshetra: { venue: "Kalakshetra Foundation", address: "Thiruvanmiyur", city: "Chennai", rows: 8, seatsPerRow: 12 },
  phoenixchn: { venue: "Phoenix Marketcity Atrium", address: "Velachery", city: "Chennai", rows: 6, seatsPerRow: 12 },
};

// [title, subtitle, category, venue key, days from today, "HH:MM" IST, minutes,
//  prices front→back, lineup, description, extras]
const EVENTS = [
  ["Afterlight", "A one-night audiovisual arena experience", "LIVE MUSIC", "nova", 4, "20:00", 150, [2499, 1899, 1499],
    [["Kavya Rao", "Headliner"], ["Lumen Collective", "Visuals"], ["DJ Arjun", "Opener"]],
    "Afterlight turns Nova Arena into a living field of sound, movement and light. Kavya Rao performs her new record in the round, beneath a circular light sculpture that answers every beat.",
    { featured: true, tags: ["Arena", "Electronic", "Visuals"] }],
  ["The Last Monsoon", "An immersive story staged in the round", "THEATRE", "ranga", 6, "19:30", 110, [1199, 899, 649],
    [["Ira Menon", "Director"], ["Rehaan Das", "Lead"]],
    "A family gathers in a crumbling coastal house as the final monsoon of the season arrives. Performed in the round with live rain effects and a string trio.",
    { tags: ["Drama", "Immersive"], language: "English, Hindi" }],
  ["Mostly Honest", "A sharp new hour by four breakout comics", "COMEDY", "shepherd", 2, "20:30", 100, [999, 799, 599],
    [["Tanvi Shah", "Stand-up"], ["Kabir Nair", "Stand-up"], ["Meera Joshi", "Stand-up"], ["Sid Varma", "Host"]],
    "Four of the country's fastest-rising comics test brand-new material on relationships, rent and family WhatsApp groups. Strictly no phones in the room.",
    { ageLimit: "16+", tags: ["Stand-up", "New material"] }],
  ["City Derby", "The loudest football night of the season", "SPORT", "kanteerava", 9, "19:00", 120, [1799, 1099, 699],
    [["Bengaluru Blues", "Home"], ["Kerala Tuskers", "Away"]],
    "Two old rivals, one sold-out stand. Expect tifos, drums and ninety minutes that decide the top of the table.",
    { featured: true, tags: ["Football", "Rivalry"] }],
  ["Astra: First Signal", "Premiere screening and cast conversation", "MOVIE", "pvr", 7, "18:30", 170, [749, 549],
    [["Nikhil Anand", "Director"], ["Sana Qureshi", "Lead cast"]],
    "Be first to see the sci-fi thriller everyone is talking about, followed by a live Q&A with the director and cast.",
    { tags: ["Premiere", "Sci-fi", "Q&A"], language: "Hindi (English subtitles)", ageLimit: "13+" }],
  ["Indigo Rooms", "An intimate jazz and soul residency", "LIVE MUSIC", "lalit", 5, "21:00", 120, [1799, 1299, 899],
    [["The Indigo Quartet", "Band"], ["Aditi Paul", "Vocals"]],
    "Candle-lit tables, a velvet stage and a quartet that plays standards the way they were meant to be heard, late and close.",
    { tags: ["Jazz", "Soul", "Late night"] }],
  ["The Night Market", "Thirty chefs, one open-air feast", "FOOD", "jayamahal", 3, "18:00", 300, [799, 499, 399],
    [["Chef Rhea Kapoor", "Curator"], ["30+ kitchens", "Stalls"]],
    "Street food legends and fine-dining chefs side by side under festoon lights. Your ticket includes five tasting tokens and a welcome drink.",
    { featured: true, tags: ["Street food", "Open air", "Tasting"] }],
  ["Frame by Frame", "A hands-on filmmaking lab", "WORKSHOP", "bic", 11, "10:00", 360, [1499, 999],
    [["Anjali Rao", "Cinematographer"], ["Varun Iyer", "Editor"]],
    "Shoot, light and cut a one-minute film in a day. Cameras provided; bring a phone and a story idea.",
    { tags: ["Filmmaking", "Hands-on"], ageLimit: "16+" }],
  ["Rhythm & Ritual", "Classical dance in a new light", "DANCE", "ncpa", 8, "19:00", 90, [1499, 1199, 799],
    [["Priya Venkatesh", "Bharatanatyam"], ["Ensemble Nritya", "Company"]],
    "Bharatanatyam reimagined with live percussion and projection mapping. A meditation on devotion, time and the body.",
    { tags: ["Classical", "Bharatanatyam"] }],
  ["Rooftop Sessions", "Indie favourites above the city", "LIVE MUSIC", "skyline", 10, "19:30", 150, [1299, 999, 799],
    [["Parallel Lines", "Band"], ["Nour", "Singer-songwriter"]],
    "Golden hour to midnight on Hyderabad's favourite rooftop. Two indie acts, one skyline and a lot of singing along.",
    { tags: ["Indie", "Rooftop"] }],
  ["New Perspectives", "An after-hours gallery opening", "ART", "knma", 12, "19:00", 150, [699, 499],
    [["Five emerging artists", "Exhibitors"], ["Roshni Mehra", "Curator"]],
    "Five emerging artists question what home means in a changing city. A curator walkthrough, live sketching and a late bar.",
    { tags: ["Contemporary", "After hours"] }],
  ["The Wonder Lab", "A science museum night for everyone", "EXHIBITION", "vism", 13, "17:00", 180, [449, 349],
    [["Dr. Kiran Bhat", "Host"]],
    "Build a rocket, walk through a giant brain and stargaze from the roof. Designed for curious kids and nostalgic adults.",
    { tags: ["Family", "Science"], ageLimit: "All ages" }],
  ["Neon Tides", "Deep house under the stars", "LIVE MUSIC", "jioworld", 14, "20:00", 240, [2999, 1999, 1299],
    [["Anyasa", "Headliner"], ["Kohra", "Support"]],
    "A six-hour open-air journey through deep and melodic house with an immersive LED canopy and a sound system tuned for the lawns.",
    { featured: true, tags: ["House", "Open air"], ageLimit: "18+" }],
  ["Kitchen Confidential", "A comedy about chefs who hate each other", "COMEDY", "habitat", 3, "21:30", 80, [899, 699],
    [["Rahul Dua", "Stand-up"], ["Aishwarya Mohanraj", "Stand-up"]],
    "Two comics who once worked in restaurant kitchens spill every secret the industry wants kept.",
    { ageLimit: "18+", tags: ["Stand-up"] }],
  ["Hamlet, Rewired", "Shakespeare for the smartphone age", "THEATRE", "opera", 16, "19:30", 140, [1999, 1499, 999],
    [["Aarav Sethi", "Hamlet"], ["The Company Theatre", "Ensemble"]],
    "Elsinore is a tech empire and every soliloquy is livestreamed. A bold, funny and heartbreaking modern Hamlet.",
    { tags: ["Shakespeare", "Modern"] }],
  ["Mumbai Marathon Expo", "Gear, talks and a pre-race pasta party", "SPORT", "wankhede", 20, "09:00", 480, [599, 399, 299],
    [["Elite runners panel", "Talks"]],
    "Everything runners need before race day: kit collection, recovery clinics and a carb-loading feast.",
    { tags: ["Running", "Expo"] }],
  ["Sufi Nights", "Qawwali under the Delhi sky", "LIVE MUSIC", "sirifort", 6, "20:00", 150, [1999, 1499, 999],
    [["Nizami Brothers", "Qawwali"]],
    "An evening of qawwali that builds from quiet devotion to ecstatic crescendo. Bring someone you love.",
    { tags: ["Sufi", "Qawwali"], language: "Urdu, Hindi" }],
  ["Tughlaq", "Girish Karnad's classic, freshly staged", "THEATRE", "kamani", 15, "19:00", 150, [999, 749, 499],
    [["Rajat Kapoor", "Director"]],
    "The idealist sultan who moved a capital and lost a kingdom. A sweeping production with a cast of thirty.",
    { tags: ["Classic", "Drama"], language: "Hindi" }],
  ["Delhi Derby Night", "Kabaddi league showdown", "SPORT", "jln", 18, "19:30", 150, [1299, 899, 499],
    [["Dabang Delhi", "Home"], ["Haryana Steelers", "Away"]],
    "The fastest-growing sport in the country, courtside. Loud, physical and over in a flash.",
    { tags: ["Kabaddi", "League"] }],
  ["Charminar Chronicles", "A heritage food walk and dinner", "FOOD", "shilpakala", 9, "18:30", 210, [1499, 1199],
    [["Chef Asif Qureshi", "Host"]],
    "Haleem, biryani and Irani chai stories told course by course, with the chefs who keep them alive.",
    { tags: ["Hyderabadi", "Dinner"] }],
  ["Stadium Lights", "T20 league night game", "SPORT", "gachibowli", 22, "19:30", 210, [2499, 1499, 799],
    [["Hyderabad Hawks", "Home"], ["Chennai Chargers", "Away"]],
    "Floodlights, fireworks and a last-over finish if we are lucky. Family stand includes free kids' caps.",
    { featured: true, tags: ["Cricket", "T20"] }],
  ["Retro Reels", "Classic Bollywood on the big screen", "MOVIE", "prasads", 5, "21:00", 180, [399, 299],
    [["Film historian Uma Rao", "Introduction"]],
    "A restored 4K print of a golden-era classic, introduced by a film historian, with a live sing-along interval.",
    { tags: ["Classic", "Restored"], language: "Hindi" }],
  ["Pune Poetry Slam", "Spoken word, open mic and a headline set", "ART", "highspirits", 4, "19:00", 150, [499, 349],
    [["Kavi Collective", "Host"], ["Open mic", "Performers"]],
    "Twelve poets, three minutes each, one winner decided by the room. Sign-ups for the open mic open at the door.",
    { tags: ["Spoken word", "Open mic"] }],
  ["Monsoon Carnival", "Music, rides and food trucks", "FOOD", "mahalaxmi", 17, "16:00", 360, [699, 499, 349],
    [["Local bands", "Live"], ["40 food trucks", "Stalls"]],
    "Pune's biggest weekend carnival returns with live bands, a giant wheel and food trucks from across the state.",
    { tags: ["Carnival", "Family"] }],
  ["Swaralaya", "Hindustani vocal recital", "LIVE MUSIC", "balgandharva", 12, "18:30", 150, [1199, 899, 599],
    [["Pt. Anand Bhate", "Vocals"], ["Tabla: Ojas Adhiya", "Accompaniment"]],
    "An evening of khayal and abhang in one of Pune's most storied halls.",
    { tags: ["Classical", "Hindustani"], language: "Marathi, Hindi" }],
  ["Margazhi Evenings", "Carnatic concert series", "LIVE MUSIC", "academy", 19, "18:00", 150, [1499, 999, 599],
    [["Sanjay Subrahmanyan", "Vocals"]],
    "The season opens with a concert of rare ragas, followed by filter coffee in the courtyard.",
    { tags: ["Carnatic", "Classical"], language: "Tamil, Telugu" }],
  ["Kathakali Tonight", "A night of epic dance-drama", "DANCE", "kalakshetra", 10, "19:00", 150, [999, 749, 499],
    [["Kalamandalam Troupe", "Company"]],
    "Towering headdresses, painted faces and stories from the Mahabharata told entirely through gesture and rhythm.",
    { tags: ["Kathakali", "Classical"] }],
  ["Design Futures", "A one-day product design sprint", "WORKSHOP", "phoenixchn", 8, "10:00", 420, [2499, 1799],
    [["Nisha Pillai", "Design lead"], ["Karthik R", "Researcher"]],
    "Go from problem to clickable prototype in a day with mentors from leading product teams. Lunch included.",
    { tags: ["UX", "Product"] }],
  ["Laugh Riot Chennai", "Tamil and English stand-up mashup", "COMEDY", "phoenixchn", 6, "20:00", 110, [799, 599],
    [["Alexander Babu", "Stand-up"], ["Praveen Kumar", "Stand-up"]],
    "Bilingual, unpredictable and very Chennai. Two comics trade sets and roast the audience (gently).",
    { tags: ["Stand-up", "Bilingual"], ageLimit: "16+" }],
  ["Lightscapes", "An immersive digital art exhibition", "EXHIBITION", "jioworld", 21, "11:00", 120, [899, 649],
    [["Studio Aura", "Artists"]],
    "Walk through rooms of light that respond to your movement. Timed entry, so every slot feels uncrowded.",
    { tags: ["Immersive", "Digital art"] }],
  ["Bollywood Unplugged", "Chart-toppers, stripped back", "LIVE MUSIC", "opera", 11, "20:00", 120, [2199, 1599, 999],
    [["Shalmali", "Vocals"], ["Acoustic ensemble", "Band"]],
    "The songs you know by heart, rearranged for strings and piano in the city's most beautiful opera house.",
    { tags: ["Bollywood", "Acoustic"], language: "Hindi" }],
  ["Street Dance Championship", "Crews battle for the national title", "DANCE", "sirifort", 23, "17:00", 210, [899, 599, 399],
    [["12 crews", "Competitors"], ["DJ Uri", "Music"]],
    "Breaking, popping and krump crews from twelve cities go head to head. Judges' finals at 8 PM.",
    { tags: ["Hip hop", "Battle"] }],
  ["Chai & Canvas", "Paint along with a pro", "WORKSHOP", "habitat", 5, "16:00", 150, [999],
    [["Tara Sen", "Artist"]],
    "Two hours, one canvas and unlimited chai. No experience needed; you leave with your own framed painting.",
    { tags: ["Painting", "Beginner friendly"] }],
  ["Indie Film Fest", "Shorts from India's new voices", "MOVIE", "bic", 15, "14:00", 240, [599, 399],
    [["Ten filmmakers", "In attendance"]],
    "Ten short films, three panels and a jury prize. Meet the filmmakers at the mixer that follows.",
    { tags: ["Festival", "Shorts"] }],
  ["Coastal Kitchen", "Konkan feast with live music", "FOOD", "ncpa", 13, "19:30", 150, [1899, 1499],
    [["Chef Gauri Desai", "Host"], ["Konkan folk trio", "Music"]],
    "Seven courses from the Konkan coast, from sol kadhi to bebinca, paired with live folk music.",
    { tags: ["Konkan", "Dinner"] }],
  ["Masters of Mridangam", "A percussion summit", "LIVE MUSIC", "academy", 26, "18:30", 120, [1299, 899, 599],
    [["Umayalpuram Sivaraman", "Mridangam"], ["Ghatam: Giridhar Udupa", "Percussion"]],
    "Legends of South Indian percussion trade rhythms in a thrilling tani avartanam showcase.",
    { tags: ["Carnatic", "Percussion"] }],
  // Recently finished: gives demo customers past tickets and organizers check-in history.
  ["Summer Sound Clash", "Two DJs, one decks, no rules", "LIVE MUSIC", "nova", -6, "20:00", 180, [1999, 1499, 999],
    [["DJ Ivy", "DJ"], ["Karan K", "DJ"]],
    "A back-to-back battle where the crowd picks the winner.",
    { tags: ["DJ", "Battle"] }],
  ["Open Air Cinema", "Cult classics on the lawns", "MOVIE", "mahalaxmi", -3, "19:30", 150, [499, 349],
    [["Pune Film Club", "Host"]],
    "Beanbags, popcorn and a cult classic under the stars.",
    { tags: ["Outdoor", "Cult"] }],
];

const IST_OFFSET_MS = 330 * 60_000;

/** Returns a Date for `daysFromToday` at HH:MM India time. */
function istDate(daysFromToday, hhmm, now = new Date()) {
  const ist = new Date(now.getTime() + IST_OFFSET_MS);
  const [h, m] = hhmm.split(":").map(Number);
  return new Date(Date.UTC(ist.getUTCFullYear(), ist.getUTCMonth(), ist.getUTCDate() + daysFromToday, h, m) - IST_OFFSET_MS);
}

export function buildSeedEvents(now = new Date()) {
  const artCursor = {};
  return EVENTS.map(([title, sub, type, venueKey, days, time, durationMins, prices, lineup, description, extra], i) => {
    const v = VENUES[venueKey];
    const arts = ART_BY_CATEGORY[type];
    artCursor[type] = (artCursor[type] ?? -1) + 1;
    return {
      seq: i + 1,
      title,
      sub,
      type,
      description,
      lineup: lineup.map(([name, role]) => ({ name, role })),
      startsAt: istDate(days, time, now),
      durationMins,
      venue: v.venue,
      address: v.address,
      city: v.city,
      layout: { rows: v.rows, seatsPerRow: v.seatsPerRow },
      tiers: buildTiers(prices, v.rows, prices.length === 1 ? ["General"] : undefined),
      blocked: pickBlockedSeats(title, v.rows, v.seatsPerRow),
      color: COLORS[i % COLORS.length],
      art: arts[artCursor[type] % arts.length],
      featured: false,
      language: "English",
      ageLimit: "All ages",
      tags: [],
      imageUrl: photoUrl(title),
      ...extra,
    };
  });
}

// The first entry is the "Demo customer" on the login page; it gets a curated set of bookings.
export const DEMO_CUSTOMERS = [
  ["Nina Kapoor", "nina@scenepass.demo", "Bengaluru"],
  ["Jay Mehta", "jay@scenepass.demo", "Mumbai"],
  ["Riya Sen", "riya@scenepass.demo", "Delhi"],
  ["Arjun Rao", "arjun@scenepass.demo", "Hyderabad"],
  ["Zoya Khan", "zoya@scenepass.demo", "Pune"],
  ["Vikram Iyer", "vikram@scenepass.demo", "Chennai"],
  ["Maya Pillai", "maya@scenepass.demo", "Bengaluru"],
  ["Dev Malhotra", "dev@scenepass.demo", "Mumbai"],
];

// A crowd of background shoppers so bookings are spread realistically.
const FIRST = ["Aarav", "Diya", "Kabir", "Ishaan", "Meera", "Rohan", "Sara", "Vihaan", "Anika", "Arnav", "Tara", "Neel"];
const LAST = ["Shah", "Nair", "Reddy", "Gupta"];
export const CROWD_CUSTOMERS = FIRST.flatMap((first, i) =>
  LAST.map((last, j) => [`${first} ${last}`, `${first}.${last}@scenepass.demo`.toLowerCase(), ["Bengaluru", "Mumbai", "Delhi", "Hyderabad", "Pune", "Chennai"][(i + j) % 6]]),
).slice(0, 40);

// Venue review snippets, [rating, comment]. Mixed so averages land between ~3.8 and 4.8.
export const REVIEW_SNIPPETS = [
  [5, "Brilliant sound and sightlines from every seat. Staff got us in quickly."],
  [5, "One of the best nights out this year. Would come back in a heartbeat."],
  [4, "Great show, slightly long queue at the bar but worth it."],
  [5, "Loved the atmosphere. Our seats in the middle rows were perfect."],
  [4, "Comfortable seating and good acoustics. Parking was a bit of a hunt."],
  [3, "Performance was good, but the venue felt a little cramped."],
  [4, "Easy entry with the QR ticket and friendly ushers."],
  [5, "Absolutely magical evening. The lighting design was stunning."],
  [4, "Solid venue, clean washrooms, decent food options."],
  [2, "Sound was muddy from the back rows. The show itself was fine."],
  [5, "Booked with friends through the group room and sat together easily."],
  [4, "Good value for the price. Started ten minutes late."],
];

// Hand-picked, license-free Unsplash photos (unsplash.com/license), one per event.
const PHOTO_IDS = {
  "Afterlight": "1514525253161-7a46d19cd819",
  "The Last Monsoon": "1503095396549-807759245b35",
  "Mostly Honest": "1527224857830-43a7acc85260",
  "City Derby": "1574629810360-7efbbe195018",
  "Astra: First Signal": "1517604931442-7e0c8ed2963c",
  "Indigo Rooms": "1415201364774-f6f0bb35f28f",
  "The Night Market": "1555939594-58d7cb561ad1",
  "Frame by Frame": "1531058020387-3be344556be6",
  "Rhythm & Ritual": "1518834107812-67b0b7c58434",
  "Rooftop Sessions": "1516450360452-9312f5e86fc7",
  "New Perspectives": "1554907984-15263bfd63bd",
  "The Wonder Lab": "1515187029135-18ee286d815b",
  "Neon Tides": "1470225620780-dba8ba36b745",
  "Kitchen Confidential": "1507676184212-d03ab07a01bf",
  "Hamlet, Rewired": "1585699324551-f6c309eedeca",
  "Mumbai Marathon Expo": "1461896836934-ffe607ba8211",
  "Sufi Nights": "1459749411175-04bf5292ceea",
  "Tughlaq": "1519683109079-d5f539e1542f",
  "Delhi Derby Night": "1501386761578-eac5c94b800a",
  "Charminar Chronicles": "1504674900247-0877df9cc836",
  "Stadium Lights": "1522778119026-d647f0596c20",
  "Retro Reels": "1489599849927-2ee91cede3ba",
  "Pune Poetry Slam": "1508700115892-45ecd05ae2ad",
  "Monsoon Carnival": "1492684223066-81342ee5ff30",
  "Swaralaya": "1524368535928-5b5e00ddc76b",
  "Margazhi Evenings": "1429962714451-bb934ecdc4ec",
  "Kathakali Tonight": "1518834107812-67b0b7c58434",
  "Design Futures": "1511578314322-379afb476865",
  "Laugh Riot Chennai": "1511671782779-c97d3d27a1d4",
  "Lightscapes": "1533174072545-7a4b6ad7a6c3",
  "Bollywood Unplugged": "1464375117522-1311d6a5b81f",
  "Street Dance Championship": "1504609813442-a8924e83f76e",
  "Chai & Canvas": "1531243269054-5ebf6f34081e",
  "Indie Film Fest": "1540575467063-178a50c2df87",
  "Coastal Kitchen": "1414235077428-338989a2e8c0",
  "Masters of Mridangam": "1470229722913-7c0e2dbbafd3",
  "Summer Sound Clash": "1540039155733-5bb30b53aa14",
  "Open Air Cinema": "1478147427282-58a87a120781",
};

export function photoUrl(title) {
  const id = PHOTO_IDS[title];
  return id ? `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&q=80` : "";
}
